language: php

cache:
  directories:
    - $HOME/.composer/cache

php:
  - '7.2'
  - '7.3'
  - '7.4'

env:
  - LARAVEL=5.5
  - LARAVEL=5.6
  - LARAVEL=5.7
  - LARAVEL=5.8
  - LARAVEL=6.0
  - LARAVEL=6.9

script:
  - vendor/bin/phpunit

before_install:
  - MINOR=`echo $LARAVEL | sed 's/[5|6]\.\([0-9]\+\)/\1/'`
  - '[[ $LARAVEL =~ ^6\.[0-9]$ ]] && MAJOR=6 || MAJOR=5'
  - composer require "illuminate/support:${MAJOR}.${MINOR}.*" --no-update -v
  - composer require "illuminate/console:${MAJOR}.${MINOR}.*" --no-update -v

install: composer install --no-interaction

notifications:
  email: false
  slack:
    secure: "oO+jXcMH0WweWH3zTNzlCTq8Ard3cdUWQrHxlIIUB3KYEnZJcsL/4QWheCjVgctI9EExgd/rATGNdYnwgFUScL2cks/qgvvzdHS35Xcpp//AKQRQTsAlj4T2ZcgbLb+pHBEBJ1U3SLgGaBITZfiHkeNO/Q4s3kcD5pq6ok1ixKYTCnSt77ELAiO77UZ6UYZV8F7GiyNY7de78XfOa6R1QT5Cza/oPLmN+AokwEvdj6KN9sQB/J8/rQx5phInYgANDRaY+mO+Vh1WbCClmd60jkFFHk1QziFZ+1c7aMV+XFbepqrF0rkWiR0S9/lafbe1RJWjpQZngNmJ15feNz6abORJOH+P+m7Z8IHeBSHw+te/r/eq1al/41BbfqhrR24Y5OORX/o6610JqDXJeg1f3ToPmi1ku5m4DGpZugvPDN817lqFzN+E+bIMZWE593KX+ylW6XPV+sGcOZNV90rTx8SA9tkD/HT/NBU6epS962k/J9eZDBjGwkGEH5Qw0fwDBXZE5Sq/iFvHcPnXncNuwo6vO4hCLTs1HeyQmEIKw/4e97EB+okkokiGuhlRr14xMCU/98wpw5GoRa1KzgdyPn1OIQY2NZbl8SxR/VzblXwiYwS11rlgOFKRz1uwStmbf3nFMHg/dmg4TQ00pXc6+KPwk8H5MAe0NFIb+pfSVn8="
